project_id = "dwxluxysruvbzxiqiynu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.chatbot]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.newsletter]
verify_jwt = false

[functions.paystack-payment]
verify_jwt = false