// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwxluxysruvbzxiqiynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3eGx1eHlzcnV2Ynp4aXFpeW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTI1MjUsImV4cCI6MjA3MTg4ODUyNX0.eeqYCYBdrm2r3qWCkV92FZJhOfqk6A8SpCk5Tz3QsHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});